#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively initialize submodules.
#------------------------------------------------------------------------------#

# Echo warning that this script is an add-on
cat << EOF
#------------------------------------------------------------------------------#
# Cinch-Utils Script
#    git-supdate
#
# Intent:
#    Initialize submodules for a project.  This script also moves
#    each submodule to its master branch so that the submodule
#    is not \"headless\".
#
# Operations:
#    git submodule foreach --recursive \"
#       git submodule init
#       git submodule update
#       git checkout master
#    \"
#------------------------------------------------------------------------------#
EOF

# This will make sure that all sub-modules are initialized
git submodule foreach --recursive "
    git submodule init
    git submodule update
    git checkout master
";
