#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively clone project.
#------------------------------------------------------------------------------#

# source function definitions
script_dir="$(dirname "$0")"
. "${script_dir}/cinch-functions"

# create description
declare -a msg=(
	""
	" Cinch-Utils Script"
	"    git-sclone"
	""
	" Intent:"
	"    Recursive clone of a git project that contains submodules."
	""
	" Operations:"
	"    git clone --recursive"
)

# print warning banner with description
print_banner $msg

# Clone the project
git clone --recursive $1
