#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to output branch ownership information
#------------------------------------------------------------------------------#

# source function definitions
script_dir="$(dirname "$0")"
. "${script_dir}/cinch-functions"

# create description
declare -a msg=(
    ""
    " Cinch-Utils Script"
    "    git-bown"
    ""
    " Intent:"
    "    List creator/owner of the branches in a repository."
    ""
    " Operations:"
    "    git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n"
)

# print warning banner with description
print_banner $msg

git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n

# vim: set tabstop=4 shiftwidth=4 expandtab :
