#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively pull latest submodule changes
#------------------------------------------------------------------------------#

# source function definitions
script_dir="$(dirname "$0")"
. "${script_dir}/cinch-functions"

# create description
declare -a msg=(
    ""
    " Cinch-Utils Script"
    "    git-spull"
    ""
    " Intent:"
    "    Pull remote changes to a git project that contains submodules."
    "    This script also moves each submodule to its master branch"
    "    so that the submodule is not \"headless\"."
    ""
    " Operations:"
    "    git submodule foreach --recursive \""
    "       branch=\`cinch-branch \$name\`"
    "       git checkout master"
    "       git pull"
    "    \""
)

# print warning banner with description
print_banner $msg

# This will make sure that all sub-modules have their latest changes
git submodule foreach --recursive '
    branch=`cinch-branch $name`
    git checkout $branch
    git pull
';

git pull

# vim: set tabstop=4 shiftwidth=4 expandtab :
