#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively update project to latest submodule heads.
#------------------------------------------------------------------------------#

# Echo warning that this script is an add-on
echo "#------------------------------------------------------------------------------#"
echo "# Cinch-Utils Script"
echo "#    git-supdate"
echo "#"
echo "# Intent:"
echo "#    Synchronize remote changes to a git project that contains"
echo "#    submodules.  This script also moves each submodule to its master"
echo "#    branch so that the submodule is not \"headless\"."
echo "#"
echo "# Operations:"
echo "#    git submodule foreach --recursive \""
echo "#       git checkout master"
echo "#       git pull"
echo "#    \""
echo "#"
echo "#    git submodule foreach --recursive \""
echo "#       git add -u;"
echo "#       git commit -m \"Updateing submodules\";"
echo "#       git push"
echo "#    \""
echo "#"
echo "#    git add -u;"
echo "#    git commit -m \"Updating submodules\";"
echo "#    git push"
echo "#------------------------------------------------------------------------------#"
echo

# This will make sure that all sub-modules have their latest changes
git submodule foreach --recursive "
    git checkout master
    git pull
";

# Commit changes to any nested submodules
git submodule foreach --recursive "
    git add -u;
    git commit -m \"Updating submodules\";
    git push
";

# Update the top-level project
git add -u;
git commit -m "Updating submodules";
git push
