#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively clone project.
#------------------------------------------------------------------------------#

# Echo warning that this script is an add-on
echo "#------------------------------------------------------------------------------#"
echo "# Cinch-Utils Script"
echo "#    git-sclone"
echo "#"
echo "# Intent:"
echo "#    Recursive clone of a git project that contains submodules."
echo "#"
echo "# Operations:"
echo "#    git clone --recursive"
echo "#------------------------------------------------------------------------------#"
echo

# Clone the project
git clone --recursive $1

# Parse off the name of the project
project=`echo $1 | perl -ne 'm,([^/:]+)\.git$, && print "$1\n"'`

# Checkout master in each submodule.  The default behavior leaves
# the submodules headless, which can be disturbing to the average user...
cd $project && git submodule foreach --recursive "
	git checkout master
";
