#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively clone project.
#------------------------------------------------------------------------------#

# Echo warning that this script is an add-on
echo "#------------------------------------------------------------------------------#"

script_dir="$(dirname "$0")"
. "${script_dir}/warning.sh"

echo "#"
echo "# Cinch-Utils Script"
echo "#    git-sclone"
echo "#"
echo "# Intent:"
echo "#    Recursive clone of a git project that contains submodules."
echo "#"
echo "# Operations:"
echo "#    git clone --recursive"
echo "#------------------------------------------------------------------------------#"
echo

# Clone the project
git clone --recursive $1
