#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively pull latest submodule changes
#------------------------------------------------------------------------------#

# source function definitions
script_dir="$(dirname "$0")"
. "${script_dir}/cinch-functions"

# create description
declare -a msg=(
	""
	" Cinch-Utils Script"
	"    git-spull"
	""
	" Intent:"
	"    Pull remote changes to a git project that contains submodules."
	""
	" Operations:"
	"    git pull"
	"    git submodule update --recursive "
)

# print warning banner with description
print_banner $msg

git pull
git submodule update --recursive
