#! /usr/bin/env bash
#------------------------------------------------------------------------------#
# git script to recursively pull latest submodule changes
#------------------------------------------------------------------------------#

# Echo warning that this script is an add-on
echo "#------------------------------------------------------------------------------#"

script_dir="$(dirname "$0")"
. "${script_dir}/warning.sh"

echo "#"
echo "# Cinch-Utils Script"
echo "#    git-spull"
echo "#"
echo "# Intent:"
echo "#    Pull remote changes to a git project that contains submodules."
echo "#"
echo "# Operations:"
echo "#    git pull"
echo "#    git submodule update --recursive "
echo "#------------------------------------------------------------------------------#"
echo

git pull
git submodule update --recursive
